#!/usr/bin/env node
// Blueprint build-stamp generator.
//
//   node tools/build-stamp/src/cli.mjs --model <dir>            # write <dir>/build.json
//   node tools/build-stamp/src/cli.mjs --model <dir> --check    # print the buildId it WOULD write, write nothing
//
// Gives a blueprint model a stable, content-addressed build identity that downstream renderers/visualizers can
// stamp on every generated artifact (so an exported diagram traces back to the exact model state it came from).
// The buildId is `<UTC-date>-<hash7>` where hash7 is the first 7 hex of a sha256 over every model *.yaml file
// under the model dir (sorted by relative path; path + content folded in) — so it changes iff the model content
// changes. Run once per model batch before committing. `--check` (exit 1 if stale) suits CI / a pre-commit hook.
// Zero runtime dependencies (node builtins only).
import { readFileSync, writeFileSync, readdirSync, statSync } from "node:fs";
import { createHash } from "node:crypto";
import path from "node:path";
import process from "node:process";

function parseArgs(argv) {
  const args = { model: path.resolve(".blueprint/v2.8"), check: false };
  for (let i = 2; i < argv.length; i += 1) {
    const token = argv[i];
    if ((token === "--model" || token === "-m") && argv[i + 1]) {
      args.model = path.resolve(argv[i + 1]);
      i += 1;
    } else if (token === "--check" || token === "-c") {
      args.check = true;
    } else if (token === "--help" || token === "-h") {
      printHelp();
      process.exit(0);
    } else {
      process.stderr.write(`Unknown argument: ${token}\n`);
      printHelp();
      process.exit(2);
    }
  }
  return args;
}

function printHelp() {
  process.stdout.write(
    "Blueprint build-stamp generator\n\n" +
    "Usage: build-stamp --model <dir> [--check]\n\n" +
    "  -m, --model <dir>  Blueprint model directory to stamp (default: .blueprint/v2.8).\n" +
    "                     Writes <dir>/build.json.\n" +
    "  -c, --check        Compute the buildId and compare to the committed build.json without\n" +
    "                     writing; exit 1 if stale (for CI / pre-commit).\n" +
    "  -h, --help         Show this help.\n\n" +
    "buildId = <UTC-date>-<sha256(model *.yaml)[0:7]> — deterministic, changes iff content changes.\n"
  );
}

// Every model *.yaml (recursively). Non-YAML working notes (*.md) drop out naturally; build.json is JSON, so it
// never feeds its own hash. Migration/decision/etc. YAML under nested dirs IS model content and is included.
function collectYaml(dir, acc = []) {
  for (const name of readdirSync(dir)) {
    const full = path.join(dir, name);
    const st = statSync(full);
    if (st.isDirectory()) collectYaml(full, acc);
    else if (name.endsWith(".yaml") || name.endsWith(".yml")) acc.push(full);
  }
  return acc;
}

function computeBuildId(modelDir) {
  const files = collectYaml(modelDir).sort((a, b) =>
    path.relative(modelDir, a).localeCompare(path.relative(modelDir, b)));
  const h = createHash("sha256");
  for (const f of files) {
    h.update(path.relative(modelDir, f).replace(/\\/g, "/"));   // OS-normalised path so renames change the hash
    h.update("\0");
    h.update(readFileSync(f));                                  // raw bytes — content
    h.update("\0");
  }
  const hash7 = h.digest("hex").slice(0, 7);
  const now = new Date();
  return { buildId: `${now.toISOString().slice(0, 10)}-${hash7}`, now, files: files.length };
}

const args = parseArgs(process.argv);
const buildFile = path.join(args.model, "build.json");

let stat;
try {
  stat = statSync(args.model);
} catch {
  process.stderr.write(`Model directory not found: ${args.model}\n`);
  process.exit(2);
}
if (!stat.isDirectory()) {
  process.stderr.write(`Not a directory: ${args.model}\n`);
  process.exit(2);
}

const { buildId, now, files } = computeBuildId(args.model);

if (args.check) {
  let current = null;
  try { current = JSON.parse(readFileSync(buildFile, "utf8")).buildId; } catch { /* no build.json yet */ }
  const stale = current !== buildId;
  process.stdout.write(`buildId (computed): ${buildId}   committed: ${current ?? "(none)"}   ${stale ? "STALE — run build-stamp" : "up-to-date"}\n`);
  process.exit(stale ? 1 : 0);
}

const record = {
  buildId,
  updatedAt: now.toISOString(),
  model: path.basename(args.model),
  files,
  note: "Generated by tools/build-stamp — buildId = <UTC-date>-<sha256(model *.yaml)[0:7]>. Run once per model batch before committing.",
};
writeFileSync(buildFile, JSON.stringify(record, null, 2) + "\n");
process.stdout.write(`buildId ${buildId}  (${files} model files)  ->  ${buildFile}\n`);
