/**
 * Atlas landing page (`docs/schema-atlas/README.md`) — the discoverable index.
 *
 * Serves as the `index` in the Atlas IA (Step 01). Names the source-of-truth
 * precedence (DEC-ATL-01/02) and the generated-vs-curated boundary so readers
 * always know what they are looking at.
 */
import type { AtlasModel } from '../types.js';
import { generatedBanner, table, blocks } from '../md.js';

export interface IndexInput {
  current: AtlasModel;
  versions: string[];
}

export function renderIndex(input: IndexInput): string {
  const { current, versions } = input;
  const parts: string[] = [generatedBanner()];
  parts.push('# Blueprint Schema Atlas');
  parts.push(
    'A **generated, human-readable projection** of the Archally Blueprint JSON Schema — layers, entity ' +
      'types, relationships, examples, and change history — so schema authors, modelers, and domain experts ' +
      'can understand the metamodel without reading raw JSON Schema.',
  );

  parts.push('> **Source of truth precedence (DEC-ATL-02):** `JSON Schema` → `overlay` → `generated projection`.\n' +
    '> JSON Schema is authoritative for all validation truth (types, requiredness, enums, relationships).\n' +
    '> Overlays add only non-authoritative human notes. **These pages are generated — do not hand-edit them;**\n' +
    '> change the schema (or an overlay) and regenerate with `npm run atlas`.');

  parts.push('## Current version');
  parts.push(`The Atlas covers **${current.version}** (current) in full, plus a cross-version changelog.`);
  parts.push(
    table(
      ['Page', 'What it answers'],
      [
        [`[Overview](./${current.version}/overview.md)`, 'What exists, at a glance, with a plane map'],
        [`[Layer map](./${current.version}/layer-map.md)`, 'Planes, files, and bounded dependency diagrams'],
        [`[Entity catalog](./${current.version}/entity-catalog.md)`, 'Every definition: properties, requiredness, enums'],
        [`[Relationships](./${current.version}/relationships.md)`, 'Typed-ID vocabulary and cross-file references'],
        [`[Examples](./${current.version}/examples.md)`, 'Schema-native and curated examples'],
        ['[Changelog](./changelog.md)', 'Schema evolution across versions'],
      ],
    ),
  );

  parts.push('## Versions');
  parts.push(
    table(
      ['Version', 'Atlas pages'],
      versions.map((v) =>
        v === current.version
          ? [`\`${v}\` (current)`, `[overview](./${v}/overview.md) · [catalog](./${v}/entity-catalog.md) · [relationships](./${v}/relationships.md)`]
          : [`\`${v}\``, '_covered in the [changelog](./changelog.md) diff path_'],
      ),
    ),
  );

  parts.push('## How this is maintained');
  parts.push(
    [
      '- **Generated by** [`tools/schema-atlas`](../../tools/schema-atlas/) from `schema/<version>/`.',
      '- **Do not hand-edit** anything under `docs/schema-atlas/` — regenerate instead.',
      '- **Governance, overlay rules, and the fail/warn/skip policy** live in the [tool README](../../tools/schema-atlas/README.md).',
      '- The root [`CHANGELOG.md`](../../CHANGELOG.md) remains the release ledger; the [Atlas changelog](./changelog.md) is the richer structural view (DEC-ATL-04).',
    ].join('\n'),
  );

  parts.push('## Related docs');
  parts.push(
    [
      '- [Schema Reference](../schema-reference.md) — hand-authored deep reference (ID patterns, traceability).',
      '- [Modeling Guide](../modeling-guide.md) — how to author a blueprint.',
      '- [`schema/`](../../schema/) — the canonical JSON Schema bundles.',
    ].join('\n'),
  );

  return blocks(...parts) + '\n';
}
