/**
 * Entity type constants for v2 blueprint model.
 * Aligned with step-01 entity kind list and traceability map.
 */
export const ENTITY_TYPE = {
  Concept: 'Concept',
  Actor: 'Actor',
  Enumeration: 'Enumeration',
  Association: 'Association',
  StructuralRule: 'StructuralRule',
  ClassificationRule: 'ClassificationRule',
  DerivationRule: 'DerivationRule',
  EquivalenceRule: 'EquivalenceRule',
  ValidationRule: 'ValidationRule',
  TransitionRule: 'TransitionRule',
  Operation: 'Operation',
  Context: 'Context',
  Service: 'Service',
  Contract: 'Contract',
  Goal: 'Goal',
  NonGoal: 'NonGoal',
  Risk: 'Risk',
  Assumption: 'Assumption',
  TradeOff: 'TradeOff',
  Inquiry: 'Inquiry',
  Decision: 'Decision',
  BusinessDecision: 'BusinessDecision',
  TestCase: 'TestCase',
  Capability: 'Capability',
  Metric: 'Metric',
  KPI: 'KPI',
  SLO: 'SLO',
  SLA: 'SLA',
  Security: 'Security',
  Compliance: 'Compliance',
  Resilience: 'Resilience',
  Finding: 'Finding',
  Story: 'Story',
  Dynamics: 'Dynamics',
  Models: 'Models',
  RG: 'RG',
  DeploymentTier: 'DeploymentTier',
  Party: 'Party',
  Department: 'Department',
  Team: 'Team',
  Screen: 'Screen',
  UIAction: 'UIAction',
  UINavigation: 'UINavigation',
  Question: 'Question',
  Error: 'Error',
  UserStory: 'UserStory',
  UseCase: 'UseCase',
  Milestone: 'Milestone',
  WorkItem: 'WorkItem',
  ValueStream: 'ValueStream',
  CodeFile: 'CodeFile',
  Missing: 'Missing',
} as const;

export type EntityType = (typeof ENTITY_TYPE)[keyof typeof ENTITY_TYPE];

/** Schema type (filename) to layer id (plane.layer). */
export const SCHEMA_TYPE_TO_LAYER: Record<string, string> = {
  concepts: 'design.concepts',
  rules: 'design.rules',
  domain: 'design.domain',
  arch: 'design.arch',
  models: 'design.models',
  story: 'design.story',
  dynamics: 'design.dynamics',
  quality: 'design.quality',
  rg: 'design.rg',
  motivation: 'governance.motivation',
  capability: 'governance.capability',
  decisions: 'governance.decisions',
  'test-cases': 'governance.tests',
  org: 'governance.org',
  ui: 'design.ui',
  roadmap: 'governance.roadmap',
  'value-stream': 'governance.value-stream',
  blueprint: 'blueprint',
};
