/**
 * Small Markdown helpers shared by the page generators.
 *
 * Determinism first (DEC-ATL-09): stable ordering, no timestamps, no volatile
 * content — generated pages must diff cleanly in git and CI.
 */

/** Banner stamped at the top of every generated file so no one hand-edits it. */
export function generatedBanner(): string {
  return '<!-- GENERATED by tools/schema-atlas — do not edit by hand. Regenerate: npm run atlas -->';
}

/** Escape a value for use inside a Markdown table cell. */
export function cell(text: string | undefined): string {
  if (!text) return '';
  return text.replace(/\r?\n+/g, ' ').replace(/\|/g, '\\|').trim();
}

/** Truncate long descriptions for table cells while staying deterministic. */
export function truncate(text: string | undefined, max = 160): string {
  if (!text) return '';
  const clean = text.replace(/\r?\n+/g, ' ').trim();
  return clean.length <= max ? clean : `${clean.slice(0, max - 1).trimEnd()}…`;
}

/** Render a Markdown table from a header row and body rows (already cell-escaped). */
export function table(header: string[], rows: string[][]): string {
  if (rows.length === 0) return '';
  const head = `| ${header.join(' | ')} |`;
  const sep = `| ${header.map(() => '---').join(' | ')} |`;
  const body = rows.map((r) => `| ${r.join(' | ')} |`);
  return [head, sep, ...body].join('\n');
}

/** Inline code, safe when empty. */
export function code(text: string | undefined): string {
  return text ? `\`${text}\`` : '';
}

/** Join blocks with blank lines, dropping empties. */
export function blocks(...parts: (string | undefined)[]): string {
  return parts.filter((p) => p && p.length > 0).join('\n\n');
}
